// Generated by commsdsl2comms v6.1.0

/// @file
/// @brief Contains definition of <b>"Interface"</b> interface class.

#pragma once

#include <tuple>
#include "comms/Message.h"
#include "comms/options.h"
#include "howto5/InterfaceCommon.h"
#include "howto5/MsgId.h"
#include "howto5/field/FieldBase.h"
#include "howto5/field/InterfaceFlags.h"
#include "howto5/field/Version.h"

namespace howto5
{

/// @brief Extra transport fields of @ref Interface interface class.
/// @see @ref Interface
/// @headerfile howto5/Interface.h
struct InterfaceFields
{
    /// @brief Definition of <b>"Version"</b> field.
    using Version =
        howto5::field::Version<
            howto5::options::DefaultOptions
        >;

    /// @brief Definition of <b>"Flags"</b> field.
    class Flags : public
        howto5::field::InterfaceFlags<
            howto5::options::DefaultOptions
        >
    {
        using Base =
            howto5::field::InterfaceFlags<
                howto5::options::DefaultOptions
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return howto5::InterfaceFieldsCommon::FlagsCommon::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Version,
        Flags
    >;
};

/// @brief Definition of <b>"Interface"</b> common interface class.
/// .incCommon Interface for all the messages. @n
/// @tparam TOpt Interface definition options
/// @headerfile howto5/Interface.h
template <typename... TOpt>
class Interface : public
    comms::Message<
        TOpt...,
        comms::option::def::BigEndian,
        comms::option::def::MsgIdType<howto5::MsgId>,
        comms::option::def::ExtraTransportFields<InterfaceFields::All>,
        comms::option::def::VersionInExtraTransportFields<0U>
    >
{
    using Base =
        comms::Message<
            TOpt...,
            comms::option::def::BigEndian,
            comms::option::def::MsgIdType<howto5::MsgId>,
            comms::option::def::ExtraTransportFields<InterfaceFields::All>,
            comms::option::def::VersionInExtraTransportFields<0U>
        >;
public:
    /// @brief Allow access to extra transport fields.
    /// @details See definition of @b COMMS_MSG_TRANSPORT_FIELDS_NAMES macro
    ///     related to @b comms::Message class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b TransportFieldIdx_version index, @b TransportField_version type
    ///         and @b transportField_version() access fuction for @ref InterfaceFields::Version field.
    ///     @li @b TransportFieldIdx_flags index, @b TransportField_flags type
    ///         and @b transportField_flags() access fuction for @ref InterfaceFields::Flags field.
    COMMS_MSG_TRANSPORT_FIELDS_NAMES(
        version,
        flags
    );
};

} // namespace howto5
