// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref howto3::message::Msg2 message and its fields.

#pragma once

namespace howto3
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref howto3::message::Msg2 message.
/// @see howto3::message::Msg2Fields
struct Msg2FieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref howto3::message::Msg2Fields::F1 field.
    struct F1Common
    {
        /// @brief Name of the @ref howto3::message::Msg2Fields::F1 field.
        static const char* name()
        {
            return "F1";
        }
    };
};

/// @brief Common types and functions of 
///     @ref howto3::message::Msg2 message.
struct Msg2Common
{
    /// @brief Name of the @ref howto3::message::Msg2 message.
    static const char* name()
    {
        return "Message 2";
    }
};

} // namespace message

} // namespace howto3
