// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "tutorial26/Version.h"

namespace tutorial26
{

/// @brief Message ids enumeration.
enum MsgId : unsigned
{
    MsgId_Msg1 = 0U,
    MsgId_Msg2 = 0U,
    MsgId_Msg3 = 0U
};

} // namespace tutorial26
