// Generated by commsdsl2comms v7.0.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref tutorial21::message::Msg2 message and its fields.

#pragma once

namespace tutorial21
{

namespace message
{

/// @brief Common types and functions of 
///     @ref tutorial21::message::Msg2 message.
struct Msg2Common
{
    /// @brief Name of the @ref tutorial21::message::Msg2 message.
    static const char* name()
    {
        return "Message 2";
    }
};

} // namespace message

} // namespace tutorial21
