// Generated by commsdsl2comms v3.6.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref tutorial2::field::S6_4 field.

#pragma once

namespace tutorial2
{

namespace field
{

/// @brief Scope for all the common definitions of the
///     @ref tutorial2::field::S6_4 field.
struct S6_4Common
{
    /// @brief Name of the @ref tutorial2::field::S6_4 field.
    static const char* name()
    {
        return "S6_4";
    }
    
};


} // namespace field

} // namespace tutorial2


