// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of the ClientInputMessages messages bundle.

#pragma once

#include <tuple>
#include "howto3/options/DefaultOptions.h"
#include "howto3/prot1/message/Prot1PseudoMsg.h"

namespace howto3
{

namespace prot1
{

namespace input
{

/// @brief Client input messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = howto3::options::DefaultOptions>
using ClientInputMessages =
    std::tuple<
        howto3::prot1::message::Prot1PseudoMsg<TBase, TOpt>
    >;

} // namespace input

} // namespace prot1

} // namespace howto3

/// @brief Create type aliases for the client input messages of the protocol.
/// @param prefix_ Prefix of the alias message type.
/// @param suffix_ Suffix of the alias message type.
/// @param interface_ Type of the common message interface.
/// @param opts_ Type of the used protocol definition options.
#define HOWTO3_PROT1_ALIASES_FOR_CLIENT_INPUT_MESSAGES(prefix_, suffix_, interface_, opts_) \
    using prefix_ ## Prot1PseudoMsg ## suffix_ = howto3::prot1::message::Prot1PseudoMsg<interface_, opts_>;

/// @brief Create type aliases for the client input messages of the protocol using default options.
/// @param prefix_ Prefix of the alias message type.
/// @param suffix_ Suffix of the alias message type.
/// @param interface_ Type of the common message interface.
#define HOWTO3_PROT1_ALIASES_FOR_CLIENT_INPUT_MESSAGES_DEFAULT_OPTIONS(prefix_, suffix_, interface_) \
    HOWTO3_PROT1_ALIASES_FOR_CLIENT_INPUT_MESSAGES(prefix_, suffix_, interface_, howto3::options::DefaultOptions)
