// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains definition of <b>"Prop4"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "comms/MessageBase.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"
#include "howto11/field/FieldBase.h"
#include "howto11/options/DefaultOptions.h"
#include "howto11/var2/message/Prop4Common.h"

namespace howto11
{

namespace var2
{

namespace message
{

/// @brief Fields of @ref Prop4.
/// @tparam TOpt Extra options
/// @see @ref Prop4
/// @headerfile howto11/var2/message/Prop4.h
template <typename TOpt = howto11::options::DefaultOptions>
struct Prop4Fields
{
    /// @brief Definition of <b>"Val"</b> field.
    class Val : public
        comms::field::IntValue<
            howto11::field::FieldBase<>,
            std::uint32_t,
            comms::option::def::HasName
        >
    {
        using Base =
            comms::field::IntValue<
                howto11::field::FieldBase<>,
                std::uint32_t,
                comms::option::def::HasName
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return howto11::var2::message::Prop4FieldsCommon::ValCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return howto11::var2::message::Prop4FieldsCommon::ValCommon::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Val
    >;
};

/// @brief Definition of <b>"Prop4"</b> message class.
/// @details
///     See @ref Prop4Fields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile howto11/var2/message/Prop4.h
template <typename TMsgBase, typename TOpt = howto11::options::DefaultOptions>
class Prop4 : public
    comms::MessageBase<
        TMsgBase,
        comms::option::def::StaticNumIdImpl<10 /* 0xa */>,
        comms::option::def::FieldsImpl<typename Prop4Fields<TOpt>::All>,
        comms::option::def::MsgType<Prop4<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            comms::option::def::StaticNumIdImpl<10 /* 0xa */>,
            comms::option::def::FieldsImpl<typename Prop4Fields<TOpt>::All>,
            comms::option::def::MsgType<Prop4<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_val index, @b Field_val type and @b field_val() access fuction
    ///         for @ref Prop4Fields::Val field.
    COMMS_MSG_FIELDS_NAMES(
        val
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 4U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 4U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return howto11::var2::message::Prop4Common::name();
    }
};

} // namespace message

} // namespace var2

} // namespace howto11
