// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref howto11::var2::message::Prop5 message and its fields.

#pragma once

namespace howto11
{

namespace var2
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref howto11::var2::message::Prop5 message.
/// @see howto11::var2::message::Prop5Fields
struct Prop5FieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref howto11::var2::message::Prop5Fields::Val field.
    struct ValCommon
    {
        /// @brief Re-definition of the value type used by
        ///     howto11::var2::message::Prop5Fields::Val field.
        using ValueType = double;

        /// @brief Name of the @ref howto11::var2::message::Prop5Fields::Val field.
        static const char* name()
        {
            return "Val";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };
};

/// @brief Common types and functions of 
///     @ref howto11::var2::message::Prop5 message.
struct Prop5Common
{
    /// @brief Name of the @ref howto11::var2::message::Prop5 message.
    static const char* name()
    {
        return "Prop5";
    }
};

} // namespace message

} // namespace var2

} // namespace howto11
