// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains definition of <b>"Prot1PseudoMsg"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "comms/MessageBase.h"
#include "comms/field/ArrayList.h"
#include "comms/options.h"
#include "howto3/field/FieldBase.h"
#include "howto3/options/DefaultOptions.h"
#include "howto3/prot1/message/Prot1PseudoMsgCommon.h"

namespace howto3
{

namespace prot1
{

namespace message
{

/// @brief Fields of @ref Prot1PseudoMsg.
/// @tparam TOpt Extra options
/// @see @ref Prot1PseudoMsg
/// @headerfile howto3/prot1/message/Prot1PseudoMsg.h
template <typename TOpt = howto3::options::DefaultOptions>
struct Prot1PseudoMsgFields
{
    /// @brief Definition of <b>"Data"</b> field.
    class Data : public
        comms::field::ArrayList<
            howto3::field::FieldBase<>,
            std::uint8_t,
            typename TOpt::prot1::message::Prot1PseudoMsgFields::Data,
            comms::option::def::HasName
        >
    {
        using Base =
            comms::field::ArrayList<
                howto3::field::FieldBase<>,
                std::uint8_t,
                typename TOpt::prot1::message::Prot1PseudoMsgFields::Data,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return howto3::prot1::message::Prot1PseudoMsgFieldsCommon::DataCommon::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Data
    >;
};

/// @brief Definition of <b>"Prot1PseudoMsg"</b> message class.
/// @details
///     See @ref Prot1PseudoMsgFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile howto3/prot1/message/Prot1PseudoMsg.h
template <typename TMsgBase, typename TOpt = howto3::options::DefaultOptions>
class Prot1PseudoMsg : public
    comms::MessageBase<
        TMsgBase,
        comms::option::def::StaticNumIdImpl<0 /* 0x0 */>,
        comms::option::def::FieldsImpl<typename Prot1PseudoMsgFields<TOpt>::All>,
        comms::option::def::MsgType<Prot1PseudoMsg<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            comms::option::def::StaticNumIdImpl<0 /* 0x0 */>,
            comms::option::def::FieldsImpl<typename Prot1PseudoMsgFields<TOpt>::All>,
            comms::option::def::MsgType<Prot1PseudoMsg<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_data index, @b Field_data type and @b field_data() access fuction
    ///         for @ref Prot1PseudoMsgFields::Data field.
    COMMS_MSG_FIELDS_NAMES(
        data
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static_assert(MsgMinLen == 0, "Unexpected min serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return howto3::prot1::message::Prot1PseudoMsgCommon::name();
    }
};

} // namespace message

} // namespace prot1

} // namespace howto3
