// Generated by commsdsl2comms v3.6.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref howto6::message::Msg1 message and its fields.

#pragma once

#include <cstdint>

namespace howto6
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref howto6::message::Msg1 message.
/// @see howto6::message::Msg1Fields
struct Msg1FieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref howto6::message::Msg1Fields::F1 field.
    struct F1Common
    {
        /// @brief Re-definition of the value type used by
        ///     howto6::message::Msg1Fields::F1 field.
        using ValueType = std::uint16_t;
    
        /// @brief Name of the @ref howto6::message::Msg1Fields::F1 field.
        static const char* name()
        {
            return "F1";
        }
        
    };
    
};

/// @brief Common types and functions of 
///     @ref howto6::message::Msg1 message.
/// @see howto6::message::Msg1
struct Msg1Common
{
    /// @brief Name of the @ref howto6::message::Msg1 message.
    static const char* name()
    {
        return "Message 1";
    }
    
};

} // namespace message

} // namespace howto6


