// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "tutorial27/Version.h"

namespace tutorial27
{

/// @brief Message ids enumeration.
enum MsgId : unsigned
{
    MsgId_sub1_Msg1 = 0,
    MsgId_sub1_Msg2 = 0,
    MsgId_sub1_Msg3 = 0,
    MsgId_sub2_Msg4 = 1,
    MsgId_sub2_Msg5 = 2,
    MsgId_sub2_Msg6 = 3
};

} // namespace tutorial27
