// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of protocol data view default options.

#pragma once

#include "howto11/options/DefaultOptions.h"

namespace howto11
{

namespace options
{

/// @brief Default data view options of the protocol.
template <typename TBase = howto11::options::DefaultOptions>
struct DataViewDefaultOptionsT : public TBase
{
    /// @brief Extra options for namespace.
    struct prot: public TBase::prot
    {
        /// @brief Extra options for messages.
        struct message : public TBase::prot::message
        {
            /// @brief Extra options for fields of
            ///     @ref howto11::prot::message::Msg1 message.
            struct Msg1Fields : public TBase::prot::message::Msg1Fields
            {
                /// @brief Extra options for @ref
                ///     howto11::prot::message::Msg1Fields::KeyValueProps
                ///     field.
                using KeyValueProps =
                    std::tuple<
                        comms::option::app::OrigDataView,
                        typename TBase::prot::message::Msg1Fields::KeyValueProps
                    >;
            };

            /// @brief Extra options for fields of
            ///     @ref howto11::prot::message::Msg2 message.
            struct Msg2Fields : public TBase::prot::message::Msg2Fields
            {
                /// @brief Extra options for @ref
                ///     howto11::prot::message::Msg2Fields::TlvProps
                ///     field.
                using TlvProps =
                    std::tuple<
                        comms::option::app::OrigDataView,
                        typename TBase::prot::message::Msg2Fields::TlvProps
                    >;
            };
        }; // struct message

        /// @brief Extra options for frames.
        struct frame : public TBase::prot::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::prot::frame::Frame frame.
            struct FrameLayers : public TBase::prot::frame::FrameLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::prot::frame::FrameLayers::DataMembers::Field field.
                struct DataMembers : public TBase::prot::frame::FrameLayers::DataMembers
                {
                    using Field =
                        std::tuple<
                            comms::option::app::OrigDataView,
                            typename TBase::prot::frame::FrameLayers::DataMembers::Field
                        >;
                }; // struct DataMembers
            }; // struct FrameLayers
        }; // struct frame
    }; // struct prot

    /// @brief Extra options for namespace.
    struct var1: public TBase::var1
    {
        /// @brief Extra options for messages.
        struct message : public TBase::var1::message
        {
            /// @brief Extra options for fields of
            ///     @ref howto11::var1::message::Prop3 message.
            struct Prop3Fields : public TBase::var1::message::Prop3Fields
            {
                /// @brief Extra options for @ref
                ///     howto11::var1::message::Prop3Fields::Val
                ///     field.
                using Val =
                    std::tuple<
                        comms::option::app::OrigDataView,
                        typename TBase::var1::message::Prop3Fields::Val
                    >;
            };
        }; // struct message

        /// @brief Extra options for frames.
        struct frame : public TBase::var1::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::var1::frame::KeyValueProp frame.
            struct KeyValuePropLayers : public TBase::var1::frame::KeyValuePropLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::var1::frame::KeyValuePropLayers::ValMembers::Field field.
                struct ValMembers : public TBase::var1::frame::KeyValuePropLayers::ValMembers
                {
                    using Field =
                        std::tuple<
                            comms::option::app::OrigDataView,
                            typename TBase::var1::frame::KeyValuePropLayers::ValMembers::Field
                        >;
                }; // struct ValMembers
            }; // struct KeyValuePropLayers
        }; // struct frame
    }; // struct var1

    /// @brief Extra options for namespace.
    struct var2: public TBase::var2
    {
        /// @brief Extra options for messages.
        struct message : public TBase::var2::message
        {
            /// @brief Extra options for fields of
            ///     @ref howto11::var2::message::Prop6 message.
            struct Prop6Fields : public TBase::var2::message::Prop6Fields
            {
                /// @brief Extra options for @ref
                ///     howto11::var2::message::Prop6Fields::Val
                ///     field.
                using Val =
                    std::tuple<
                        comms::option::app::OrigDataView,
                        typename TBase::var2::message::Prop6Fields::Val
                    >;
            };
        }; // struct message

        /// @brief Extra options for frames.
        struct frame : public TBase::var2::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::var2::frame::TlvProp frame.
            struct TlvPropLayers : public TBase::var2::frame::TlvPropLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::var2::frame::TlvPropLayers::ValMembers::Field field.
                struct ValMembers : public TBase::var2::frame::TlvPropLayers::ValMembers
                {
                    using Field =
                        std::tuple<
                            comms::option::app::OrigDataView,
                            typename TBase::var2::frame::TlvPropLayers::ValMembers::Field
                        >;
                }; // struct ValMembers
            }; // struct TlvPropLayers
        }; // struct frame
    }; // struct var2
};

/// @brief Alias to @ref DataViewDefaultOptionsT with default template parameter.
using DataViewDefaultOptions = DataViewDefaultOptionsT<>;

} // namespace options

} // namespace howto11
