// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of protocol server input messages dynamic memory allocation message factory options.

#pragma once

#include "howto11/options/DefaultOptions.h"
#include "howto11/prot/factory/ServerInputMessagesDynMemMsgFactory.h"
#include "howto11/var1/factory/ServerInputMessagesDynMemMsgFactory.h"
#include "howto11/var2/factory/ServerInputMessagesDynMemMsgFactory.h"

namespace howto11
{

namespace options
{

/// @brief Provided server input messages dynamic memory allocation message factory options of the protocol.
/// @details Must be used as the outermost wrapper of the protocol options.
template <typename TBase = howto11::options::DefaultOptions>
struct ServerInputMessagesDynMemMsgFactoryDefaultOptionsT : public TBase
{
    /// @brief Alias to actual message factory class.
    /// @details Exposes the same template parameters as @b comms::MsgFactory.
    template <typename TInterface, typename TAllMessages, typename... TOptions>
    using prot_MsgFactory =
        howto11::prot::factory::ServerInputMessagesDynMemMsgFactory<TInterface, ServerInputMessagesDynMemMsgFactoryDefaultOptionsT<TBase> >;

    /// @brief Alias to actual message factory class.
    /// @details Exposes the same template parameters as @b comms::MsgFactory.
    template <typename TInterface, typename TAllMessages, typename... TOptions>
    using var1_MsgFactory =
        howto11::var1::factory::ServerInputMessagesDynMemMsgFactory<TInterface, ServerInputMessagesDynMemMsgFactoryDefaultOptionsT<TBase> >;

    /// @brief Alias to actual message factory class.
    /// @details Exposes the same template parameters as @b comms::MsgFactory.
    template <typename TInterface, typename TAllMessages, typename... TOptions>
    using var2_MsgFactory =
        howto11::var2::factory::ServerInputMessagesDynMemMsgFactory<TInterface, ServerInputMessagesDynMemMsgFactoryDefaultOptionsT<TBase> >;

    /// @brief Extra options for namespace.
    struct prot: public TBase::prot
    {
        /// @brief Extra options for frames.
        struct frame : public TBase::prot::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::prot::frame::Frame frame.
            struct FrameLayers : public TBase::prot::frame::FrameLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::prot::frame::FrameLayers::ID
                ///     layer.
                using ID =
                    std::tuple<
                        comms::option::app::MsgFactoryTempl<prot_MsgFactory>,
                        typename TBase::prot::frame::FrameLayers::ID
                    >;
            }; // struct FrameLayers
        }; // struct frame
    }; // struct prot

    /// @brief Extra options for namespace.
    struct var1: public TBase::var1
    {
        /// @brief Extra options for frames.
        struct frame : public TBase::var1::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::var1::frame::KeyValueProp frame.
            struct KeyValuePropLayers : public TBase::var1::frame::KeyValuePropLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::var1::frame::KeyValuePropLayers::Key
                ///     layer.
                using Key =
                    std::tuple<
                        comms::option::app::MsgFactoryTempl<var1_MsgFactory>,
                        typename TBase::var1::frame::KeyValuePropLayers::Key
                    >;
            }; // struct KeyValuePropLayers
        }; // struct frame
    }; // struct var1

    /// @brief Extra options for namespace.
    struct var2: public TBase::var2
    {
        /// @brief Extra options for frames.
        struct frame : public TBase::var2::frame
        {
            /// @brief Extra options for layers of
            ///     @ref howto11::var2::frame::TlvProp frame.
            struct TlvPropLayers : public TBase::var2::frame::TlvPropLayers
            {
                /// @brief Extra options for @ref
                ///     howto11::var2::frame::TlvPropLayers::Key
                ///     layer.
                using Key =
                    std::tuple<
                        comms::option::app::MsgFactoryTempl<var2_MsgFactory>,
                        typename TBase::var2::frame::TlvPropLayers::Key
                    >;
            }; // struct TlvPropLayers
        }; // struct frame
    }; // struct var2
};

/// @brief Alias to @ref ServerInputMessagesDynMemMsgFactoryDefaultOptionsT with default template parameter.
using ServerInputMessagesDynMemMsgFactoryDefaultOptions = ServerInputMessagesDynMemMsgFactoryDefaultOptionsT<>;

} // namespace options

} // namespace howto11
