// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of <b>"Message 2"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "comms/MessageBase.h"
#include "comms/field/ArrayList.h"
#include "comms/options.h"
#include "howto11/field/FieldBase.h"
#include "howto11/options/DefaultOptions.h"
#include "howto11/prot/message/Msg2Common.h"

namespace howto11
{

namespace prot
{

namespace message
{

/// @brief Fields of @ref Msg2.
/// @tparam TOpt Extra options
/// @see @ref Msg2
/// @headerfile howto11/prot/message/Msg2.h
template <typename TOpt = howto11::options::DefaultOptions>
struct Msg2Fields
{
    /// @brief Definition of <b>"TlvProps"</b> field.
    class TlvProps : public
        comms::field::ArrayList<
            howto11::field::FieldBase<>,
            std::uint8_t,
            typename TOpt::prot::message::Msg2Fields::TlvProps,
            comms::option::def::HasName
        >
    {
        using Base =
            comms::field::ArrayList<
                howto11::field::FieldBase<>,
                std::uint8_t,
                typename TOpt::prot::message::Msg2Fields::TlvProps,
                comms::option::def::HasName
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return howto11::prot::message::Msg2FieldsCommon::TlvPropsCommon::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        TlvProps
    >;
};

/// @brief Definition of <b>"Message 2"</b> message class.
/// @details
///     See @ref Msg2Fields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile howto11/prot/message/Msg2.h
template <typename TMsgBase, typename TOpt = howto11::options::DefaultOptions>
class Msg2 : public
    comms::MessageBase<
        TMsgBase,
        comms::option::def::StaticNumIdImpl<2 /* 0x2 */>,
        comms::option::def::FieldsImpl<typename Msg2Fields<TOpt>::All>,
        comms::option::def::MsgType<Msg2<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            comms::option::def::StaticNumIdImpl<2 /* 0x2 */>,
            comms::option::def::FieldsImpl<typename Msg2Fields<TOpt>::All>,
            comms::option::def::MsgType<Msg2<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_tlvProps index, @b Field_tlvProps type and @b field_tlvProps() access fuction
    ///         for @ref Msg2Fields::TlvProps field.
    COMMS_MSG_FIELDS_NAMES(
        tlvProps
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static_assert(MsgMinLen == 0, "Unexpected min serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return howto11::prot::message::Msg2Common::name();
    }
};

} // namespace message

} // namespace prot

} // namespace howto11
