// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref howto11::prot::message::Msg2 message and its fields.

#pragma once

namespace howto11
{

namespace prot
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref howto11::prot::message::Msg2 message.
/// @see howto11::prot::message::Msg2Fields
struct Msg2FieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref howto11::prot::message::Msg2Fields::TlvProps field.
    struct TlvPropsCommon
    {
        /// @brief Name of the @ref howto11::prot::message::Msg2Fields::TlvProps field.
        static const char* name()
        {
            return "TlvProps";
        }
    };
};

/// @brief Common types and functions of 
///     @ref howto11::prot::message::Msg2 message.
struct Msg2Common
{
    /// @brief Name of the @ref howto11::prot::message::Msg2 message.
    static const char* name()
    {
        return "Message 2";
    }
};

} // namespace message

} // namespace prot

} // namespace howto11
