// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref tutorial26::message::Msg2 message and its fields.

#pragma once

namespace tutorial26
{

namespace message
{

/// @brief Common types and functions of 
///     @ref tutorial26::message::Msg2 message.
struct Msg2Common
{
    /// @brief Name of the @ref tutorial26::message::Msg2 message.
    static const char* name()
    {
        return "Message 2";
    }
};

} // namespace message

} // namespace tutorial26
