// Generated by commsdsl2comms v3.6.4

/// @file
/// @brief Contains definition of <b>"SyncField"</b> field.

#pragma once

#include <cstdint>
#include "comms/field/IntValue.h"
#include "comms/options.h"
#include "howto9/field/FieldBase.h"
#include "howto9/field/SyncFieldCommon.h"
#include "howto9/options/DefaultOptions.h"

namespace howto9
{

namespace field
{

/// @brief Definition of <b>"SyncField"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = howto9::options::DefaultOptions, typename... TExtraOpts>
struct SyncField : public
    comms::field::IntValue<
        howto9::field::FieldBase<>,
        std::uint16_t,
        TExtraOpts...,
        comms::option::def::DefaultNumValue<43981L>
    >
{
    /// @brief Name of the field.
    static const char* name()
    {
        return howto9::field::SyncFieldCommon::name();
    }
    
};

} // namespace field

} // namespace howto9


