// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains definition of <b>"Prop3"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "comms/MessageBase.h"
#include "comms/field/IntValue.h"
#include "comms/field/String.h"
#include "comms/options.h"
#include "howto11/field/FieldBase.h"
#include "howto11/options/DefaultOptions.h"
#include "howto11/var1/message/Prop3Common.h"

namespace howto11
{

namespace var1
{

namespace message
{

/// @brief Fields of @ref Prop3.
/// @tparam TOpt Extra options
/// @see @ref Prop3
/// @headerfile howto11/var1/message/Prop3.h
template <typename TOpt = howto11::options::DefaultOptions>
struct Prop3Fields
{
    /// @brief Scope for all the member fields of
    ///     @ref Val field.
    struct ValMembers
    {
        /// @brief Definition of <b>"Length"</b> field.
        class Length : public
            comms::field::IntValue<
                howto11::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::HasName
            >
        {
            using Base =
                comms::field::IntValue<
                    howto11::field::FieldBase<>,
                    std::uint8_t,
                    comms::option::def::HasName
                >;
        public:
            /// @brief Re-definition of the value type.
            using ValueType = typename Base::ValueType;

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return howto11::var1::message::Prop3FieldsCommon::ValMembersCommon::LengthCommon::hasSpecials();
            }

            /// @brief Name of the field.
            static const char* name()
            {
                return howto11::var1::message::Prop3FieldsCommon::ValMembersCommon::LengthCommon::name();
            }
        };
    };

    /// @brief Definition of <b>"Val"</b> field.
    class Val : public
        comms::field::String<
            howto11::field::FieldBase<>,
            typename TOpt::var1::message::Prop3Fields::Val,
            comms::option::def::HasName,
            comms::option::def::SequenceSerLengthFieldPrefix<typename ValMembers::Length>
        >
    {
        using Base =
            comms::field::String<
                howto11::field::FieldBase<>,
                typename TOpt::var1::message::Prop3Fields::Val,
                comms::option::def::HasName,
                comms::option::def::SequenceSerLengthFieldPrefix<typename ValMembers::Length>
            >;
    public:
        /// @brief Name of the field.
        static const char* name()
        {
            return howto11::var1::message::Prop3FieldsCommon::ValCommon::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Val
    >;
};

/// @brief Definition of <b>"Prop3"</b> message class.
/// @details
///     See @ref Prop3Fields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile howto11/var1/message/Prop3.h
template <typename TMsgBase, typename TOpt = howto11::options::DefaultOptions>
class Prop3 : public
    comms::MessageBase<
        TMsgBase,
        comms::option::def::StaticNumIdImpl<5 /* 0x5 */>,
        comms::option::def::FieldsImpl<typename Prop3Fields<TOpt>::All>,
        comms::option::def::MsgType<Prop3<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            comms::option::def::StaticNumIdImpl<5 /* 0x5 */>,
            comms::option::def::FieldsImpl<typename Prop3Fields<TOpt>::All>,
            comms::option::def::MsgType<Prop3<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_val index, @b Field_val type and @b field_val() access fuction
    ///         for @ref Prop3Fields::Val field.
    COMMS_MSG_FIELDS_NAMES(
        val
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static_assert(MsgMinLen == 1, "Unexpected min serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return howto11::var1::message::Prop3Common::name();
    }
};

} // namespace message

} // namespace var1

} // namespace howto11
