// Generated by commsdsl2comms v8.1.0

/// @file
/// @brief Contains definition of protocol bare metal default options.

#pragma once

#include "tutorial27/options/DefaultOptions.h"

#ifndef DEFAULT_SEQ_FIXED_STORAGE_SIZE
/// @brief Define default fixed size for various sequence fields
/// @details May be defined during compile time to change the default value.
#define DEFAULT_SEQ_FIXED_STORAGE_SIZE 32
#endif

namespace tutorial27
{

namespace options
{

/// @brief Default bare metal options of the protocol.
template <typename TBase = tutorial27::options::DefaultOptions>
struct BareMetalDefaultOptionsT : public TBase
{
    /// @brief Extra options for namespace.
    struct sub1: public TBase::sub1
    {
        /// @brief Extra options for frames.
        struct frame : public TBase::sub1::frame
        {
            /// @brief Extra options for layers of
            ///     @ref tutorial27::sub1::frame::Frame frame.
            struct FrameLayers : public TBase::sub1::frame::FrameLayers
            {
                /// @brief Extra options for @ref
                ///     tutorial27::sub1::frame::FrameLayers::DataMembers::Field field.
                struct DataMembers : public TBase::sub1::frame::FrameLayers::DataMembers
                {
                    using Field =
                        std::tuple<
                            comms::option::app::FixedSizeStorage<DEFAULT_SEQ_FIXED_STORAGE_SIZE * 8>,
                            typename TBase::sub1::frame::FrameLayers::DataMembers::Field
                        >;
                }; // struct DataMembers

                /// @brief Extra options for @ref
                ///     tutorial27::sub1::frame::FrameLayers::Id
                ///     layer.
                using Id =
                    std::tuple<
                        comms::option::app::InPlaceAllocation,
                        typename TBase::sub1::frame::FrameLayers::Id
                    >;
            }; // struct FrameLayers
        }; // struct frame
    }; // struct sub1

    /// @brief Extra options for namespace.
    struct sub2: public TBase::sub2
    {
        /// @brief Extra options for frames.
        struct frame : public TBase::sub2::frame
        {
            /// @brief Extra options for layers of
            ///     @ref tutorial27::sub2::frame::Frame frame.
            struct FrameLayers : public TBase::sub2::frame::FrameLayers
            {
                /// @brief Extra options for @ref
                ///     tutorial27::sub2::frame::FrameLayers::DataMembers::Field field.
                struct DataMembers : public TBase::sub2::frame::FrameLayers::DataMembers
                {
                    using Field =
                        std::tuple<
                            comms::option::app::FixedSizeStorage<DEFAULT_SEQ_FIXED_STORAGE_SIZE * 8>,
                            typename TBase::sub2::frame::FrameLayers::DataMembers::Field
                        >;
                }; // struct DataMembers

                /// @brief Extra options for @ref
                ///     tutorial27::sub2::frame::FrameLayers::Id
                ///     layer.
                using Id =
                    std::tuple<
                        comms::option::app::InPlaceAllocation,
                        typename TBase::sub2::frame::FrameLayers::Id
                    >;
            }; // struct FrameLayers
        }; // struct frame
    }; // struct sub2
};

/// @brief Alias to @ref BareMetalDefaultOptionsT with default template parameter.
using BareMetalDefaultOptions = BareMetalDefaultOptionsT<>;

} // namespace options

} // namespace tutorial27
