// Generated by commsdsl2comms v3.4.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref tutorial9::message::Msg3 message and its fields.

#pragma once

namespace tutorial9
{

namespace message
{

/// @brief Common types and functions of 
///     @ref tutorial9::message::Msg3 message.
/// @see tutorial9::message::Msg3
struct Msg3Common
{
    /// @brief Name of the @ref tutorial9::message::Msg3 message.
    static const char* name()
    {
        return "Message 3";
    }
    
};

} // namespace message

} // namespace tutorial9


