// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref tutorial27::sub2::message::Msg4 message and its fields.

#pragma once

namespace tutorial27
{

namespace sub2
{

namespace message
{

/// @brief Common types and functions of 
///     @ref tutorial27::sub2::message::Msg4 message.
struct Msg4Common
{
    /// @brief Name of the @ref tutorial27::sub2::message::Msg4 message.
    static const char* name()
    {
        return "Message 4";
    }
};

} // namespace message

} // namespace sub2

} // namespace tutorial27
